export const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const SAVE_USER_TO_PREVIEW = "SAVE_USER_TO_PREVIEW";
export const SET_AUDIENCE_LIST = "SET_AUDIENCE_LIST";
export const EMPTY_AUDIENCE_LIST = "EMPTY_AUDIENCE_LIST";
export const SET_PAGE_TO_HOME = "SET_PAGE_TO_HOME";
export const SET_PAGE_TO_PROFILE = "SET_PAGE_TO_PROFILE";
export const SET_PAGE_TO_JOBS = "SET_PAGE_TO_JOBS";
export const SET_SUBPAGE_TO_ABOUT = "SET_SUBPAGE_TO_ABOUT";
export const SET_SUBPAGE_TO_AUDIENCE = "SET_SUBPAGE_TO_AUDIENCE";
export const SET_SUBPAGE_TO_SKILLS = "SET_SUBPAGE_TO_SKILLS";
export const SET_SUBPAGE_TO_SETTINGS = "SET_SUBPAGE_TO_SETTINGS";
export const SET_SUBPAGE_TO_ = "SET_SUBPAGE_TO_";
export const SET_SEARCH_RESULT_TO_LIST = "SET_SEARCH_RESULT";
export const SET_SEARCH_RESULT_TO_NOT_FOUND = "SET_SEARCH_RESULT_TO_NOT_FOUND";
export const UPDATE_HAS_NEXT_PAGE = "UPDATE_HAS_NEXT_PAGE";
export const LOADING = "LOADING";
export const  SET_JOBS = "SET_JOBS";
export const JOBS_SET_ERROR = "JOBS_SET_ERROR";









