export const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const SAVE_USER_TO_PREVIEW = "SAVE_USER_TO_PREVIEW";
export const SET_AUDIENCE_LIST = "SET_AUDIENCE_LIST";
export const EMPTY_AUDIENCE_LIST = "EMPTY_AUDIENCE_LIST";
export const SET_SEARCH_RESULT_TO_LIST = "SET_SEARCH_RESULT";
export const SET_SEARCH_RESULT_TO_NOT_FOUND = "SET_SEARCH_RESULT_TO_NOT_FOUND";
export const UPDATE_HAS_NEXT_PAGE = "UPDATE_HAS_NEXT_PAGE";
export const LOADING = "LOADING";









